/******************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: ultrasonic_sensor.h
 *
 * Description: Header file for the AVR Ultrasonic Sensor driver
 *
 * Author: Salma AbdelMonem
 *
 *******************************************************************************/
#ifndef ULTRASONIC_SENSOR_H_
#define ULTRASONIC_SENSOR_H_

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description : Function to initialize the Ultrasonic Sensor driver.
 * 	1. Initialize the ICU driver as required.
 * 	2. Setup the ICU call back function.
 * 	3. Setup the direction for the trigger pin.
 */
void Ultrasonic_init(void);

/*
 * Description : Function to trigger the Ultrasonic Sensor driver.
 * 	1. Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);

/*
 * Description : Function to read distance from the Ultrasonic Sensor driver.
 * 	1. Send the trigger pulse by using Ultrasonic_Trigger function.
 * 	2. Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description : Function to get high time of edge.
 * 	1. This is the call back function called by the ICU driver.
 * 	2. This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif
